### ISSUE TITLE
Error on downloads/delete REST API

### ISSUE THREAD

**Issue by machao81** [razorxan/node-real-debrid#3]
The delete of a link is not woirking because of line
return this._get('downloads/delete/' + id).

It works correctly with the line 
return this._delete('downloads/delete/' + id)

**Comment by machao81** [comment]
i can not push on the git repository so i show you

![image](https://user-images.githubusercontent.com/7334628/46410619-bb94c880-c719-11e8-982d-175251996f4b.png)

Could you create a new version please ?

**Comment by razorxan** [comment]
fixed
